---
ID: "e2b7708b-7a3f-449e-96a2-ad029d333176"
Parent: "9e459de5-0d5a-458a-be73-344b939719e1"
Template: "9e459de5-0d5a-458a-be73-344b939719e1"
Path: /sitecore/templates/Project/LionTrust/Content Types/Header Dropdown/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210406T122838Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
