---
ID: "831d4051-2a8d-4f1b-a6e2-73e1e88c3f70"
Parent: "de347e52-3823-4c3d-96a5-6dda2dcf0d85"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/content/LionTrustNew/Global/Search Configuration
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{96A5AEBE-DE87-4F9F-9F0F-740395A3FDC9}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210623T084333Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
