---
ID: "96073fc5-55c0-4ba1-a16c-1b1b48a563fa"
Parent: "2c310f46-93ca-4625-b37d-278ab19136b1"
Template: "2c310f46-93ca-4625-b37d-278ab19136b1"
Path: /sitecore/templates/Project/EIT/Content Types/Article/Article Text/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221121T165210Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
