image: node:latest

pipelines:
  custom:
    lighthouse-checks:
      - step:
          name: Lighthouse Checks
          caches:
            - node
          script:
            - apt-get update && apt-get install apt-transport-https -y
            - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            - sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            - apt-get update && apt-get install google-chrome-stable -y
            - npm i -g @lhci/cli@"^0.7.0"
            - lhci healthcheck
            - lhci collect --url $LIGHTHOUSE_URL
            - lhci assert
            - mv .lighthouseci lighthouse-results
          artifacts:
            - lighthouse-results/**