---
ID: "e05deb20-ab57-4393-aee3-013ba79a70bc"
Parent: "f89d20bd-3b5c-4755-8e85-0edbbc875887"
Template: "f89d20bd-3b5c-4755-8e85-0edbbc875887"
Path: /sitecore/templates/Project/LionTrust/Content Types/Fund/Award/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140919T122945
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
