---
ID: "cd1590e1-6573-4cc7-b0a9-e3bb6a9dade4"
Parent: "bbd9542d-3020-4ab5-89f9-1e974b24d870"
Template: "3a45a723-64ee-4919-9d41-02fd40fd1466"
Path: /sitecore/layout/layouts/Project/LionTrust/Default
DB: master
SharedFields:
- ID: "a036b2bc-ba04-44f6-a75f-bae6cd242abf"
  Hint: Path
  Value: /Views/Layouts/LionTrust/Default.cshtml
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170212T143510Z
