---
ID: "8362f08b-c427-4b66-b703-eb98ac1d9183"
Parent: "4be83316-f916-42c3-ac15-e86c6ad5b215"
Template: "73f15617-f8d0-46fc-a4be-11948d22e59b"
Path: /sitecore/content/LionTrustNew/Page Settings/Footer Configuration
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{14110444-2160-48E7-8B8D-1807A901C997}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "05aba786-3d35-479b-ada4-ecee716ad9f5"
      Hint: FooterConfiguration_FindUsLabel
      Value: Find us
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210406T121357Z
    - ID: "25fe6d9f-7990-451a-a9cb-94a632389cd3"
      Hint: FooterConfiguration_SubscribeCTALink
      Value: |
        <link linktype="external" url="http://www.google.com" anchor="" target="" />
    - ID: "580a13a4-8095-4815-be0a-2888c67a8aeb"
      Hint: FooterConfiguration_PostalCode
      Value: WC2R 0EZ
    - ID: "5d9590c5-5dbe-47a1-b617-634debc799c5"
      Hint: FooterConfiguration_PhoneNumber
      Value: +44 (0)20 7412 1700
    - ID: "a4f06287-e1be-4c76-96d8-e0e8b609aac1"
      Hint: FooterConfiguration_GoogleMapsLink
      Value: |
        <link linktype="external" url="http://www.google.com" anchor="" target="" />
    - ID: "c77b9712-2755-4657-bdf2-c43aed9bee02"
      Hint: FooterConfiguration_Location
      Value: London
    - ID: "d77b2873-db24-4887-9db1-af3bcd76f3d6"
      Hint: FooterConfiguration_Email
      Value: test@test.com
    - ID: "e28b0c65-2dc9-42cb-b852-282c57bfee3a"
      Hint: FooterConfiguration_Page Links
      Type: Treelist
      Value: |
        {51723723-E912-4A96-8DB3-391795910F30}
        {852F4008-8C74-4328-8E27-C0212DED15AE}
        {94067DB5-9D55-450A-A285-A3DA1399DC56}
    - ID: "f0d67b9b-4d7d-40ac-b854-ac936934071d"
      Hint: FooterConfiguration_Social Links
      Type: Treelist
      Value: |
        {5976C22F-9F0A-4330-9C4B-5B8030C0EDB7}
        {9684486B-7593-40C7-82B7-4B4F990F8FD5}
        {3938BBEF-AED2-4F61-8569-2AEDA9057845}
    - ID: "f53df5de-4d7d-4278-8dae-59d0c79d0b0c"
      Hint: FooterConfiguration_Address
      Value: 2 Savoy Court
