---
ID: "02cc60d2-31a5-43a7-acda-5f8c08832abb"
Parent: "dadec9bf-b6e8-4e04-a082-f4eb20b76ff9"
Template: "dadec9bf-b6e8-4e04-a082-f4eb20b76ff9"
Path: /sitecore/templates/Project/LionTrust/Content Types/Fund/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140919T112402Z
    - ID: "584da03f-117f-476d-8b0d-079a215f1b37"
      Hint: SectorLabel
      Value: IA sector
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "9238823c-d3a1-4b63-940c-867e606716aa"
      Hint: HistoricYieldText
      Value: "<p><strong>Historic Yield:</strong> Reflects distributions declared over the past 12 months as a percentage of the mid-market unit price. It does not include any preliminary charge and investors may be subject to tax on their distributions.</p>"
    - ID: "b3e71185-b6c6-44f9-8b44-902957935bba"
      Hint: ActiveShareText
      Value: "<p><strong>Active Share:</strong> The fraction of a portfolio invested differently to its benchmark. A 100% active share is a portfolio with no holdings in the benchmark, a 0% active share is a portfolio identical to the benchmark.</p>"
