---
ID: "88fea9ea-573b-45c2-be1c-c6be80af8462"
Parent: "0bd7dd18-3839-45a6-913a-7cff529016cc"
Template: "0bd7dd18-3839-45a6-913a-7cff529016cc"
Path: /sitecore/templates/Project/EIT/Content Types/Fund/Fund Manager Promo/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221121T171820Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
