---
ID: "ad79e53a-ddf4-42be-a89c-8475482b2092"
Parent: "8b530076-6e7b-47e3-8fdd-3b4642c99df6"
Template: "8b530076-6e7b-47e3-8fdd-3b4642c99df6"
Path: /sitecore/templates/Project/LionTrust/Content Types/Navigation/CTA Link/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210528T155712Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
