---
ID: "cb9259d8-6351-48fd-8bd5-bb66e1535db0"
Parent: "8eed9726-6d66-43bb-8e6c-f31112576360"
Template: "8eed9726-6d66-43bb-8e6c-f31112576360"
Path: /sitecore/templates/Project/EIT/Content Types/Fund/Fund Region/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210623T122803Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "69dc0a58-c81a-4318-b387-ff8361d4f3a1"
      Hint: FundRegion_Name
      Value: $name
