---
ID: "2828fca3-dd56-4c10-80ff-77b3bad62682"
Parent: "73f15617-f8d0-46fc-a4be-11948d22e59b"
Template: "73f15617-f8d0-46fc-a4be-11948d22e59b"
Path: /sitecore/templates/Project/LionTrust/Content Types/Footer Configuration/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210406T120041Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
