---
ID: "b427cf92-643f-4ada-9151-7af55946f71b"
Parent: "5fa772fc-ea92-47c5-b62c-378240f761f7"
Template: "5fa772fc-ea92-47c5-b62c-378240f761f7"
Path: /sitecore/templates/Project/LionTrust/Content Types/ArticlePodcastPromo/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Apps/32x32/Microphone.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{95B7738C-E36D-4F6E-BD5E-6E2C5D049940}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210513T065003Z
    - ID: "3e49d1a6-bc8a-4924-a77d-ad0966d104ea"
      Hint: PodcastPromo_PodcastsLabel
      Value: "Listen on:"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "b43132db-b2c9-400f-b79c-2dee790e100b"
      Hint: PodcastPromo_Title
      Value: $name
