---
ID: "3c93b568-eaa7-4553-a625-4bf6c23fc400"
Parent: "bc775c7d-48c1-4f1b-865a-fecab210dbe3"
Template: "bc775c7d-48c1-4f1b-865a-fecab210dbe3"
Path: /sitecore/templates/Project/LionTrust/Content Types/PagePromoItem/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1058a56c-86ff-4783-a8d2-00c2217cc7ff"
      Hint: PagePromoItem_Heading
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210528T114632Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
