---
ID: "5ff4d6f5-2aaa-4ee6-9d40-46a4b200dd10"
Parent: "6dddca01-92ca-4c15-b50e-a80c6e05c959"
Template: "6dddca01-92ca-4c15-b50e-a80c6e05c959"
Path: /sitecore/templates/Project/LionTrust/Content Types/Navigation/HomePageCarousel/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{4E106225-A950-4B0C-8DC0-2092D4897B63}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210421T113829Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
