---
ID: "cd2e9add-f3dd-4ce8-baa1-b2aae971bbb8"
Parent: "68e1e587-6beb-4217-a075-fdfe877115cb"
Template: "68e1e587-6beb-4217-a075-fdfe877115cb"
Path: /sitecore/templates/Project/EIT/Content Types/Banner/Two CTAs/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221121T120946Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
