---
ID: "c5d6d9ad-bde2-46a1-be3d-9b306b5cddf8"
Parent: "ba71d966-969a-4eea-b454-e615b19adc5a"
Template: "ba71d966-969a-4eea-b454-e615b19adc5a"
Path: /sitecore/templates/Project/EIT/Content Types/Navigation/Copy With Cta/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221121T171512Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
