---
ID: "9e18dcc3-d8ed-49f2-82bc-be4e9c2a94f2"
Parent: "1d5fe6cd-b369-4898-ba2f-7c4630504457"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Feature/Navigation/_FooterConfiguration/Footer Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210406T115850Z
