---
ID: "1bc6cc70-9a78-42ce-9e70-e1b19d407d13"
Parent: "078d8a76-f971-4891-b422-76c0bcf9fa03"
Template: "078d8a76-f971-4891-b422-76c0bcf9fa03"
Path: /sitecore/templates/System/Email/Messages/AB Test Message/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120622T113912
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
