---
ID: "b4de9d10-2221-47be-857d-465a1616e7f0"
Parent: "68ed9154-702a-4d18-a718-4bcc5ac1d5e6"
Template: "68ed9154-702a-4d18-a718-4bcc5ac1d5e6"
Path: /sitecore/templates/Project/LionTrust/Page Types/Preference Centre/Edit Preferences/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211006T084935Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
