---
ID: "4a17b879-0909-4b19-bd38-e09c3f989ce1"
Parent: "22640263-ed61-4320-91e8-3057f25d6e2c"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/Foundation/Onboarding/_OnboardingConfiguration/Onboarding Configuration/OnboardingConfiguration_ProfessionalPatternCard
DB: master
SharedFields:
- ID: "1eb8ae32-e190-44a6-968d-ed904c794ebf"
  Hint: Source
  Value: "query:/sitecore/system/Marketing Control Panel/Profiles//*[@@tid='{4A6A7E36-2481-438F-A9BA-0453ECC638FA}']"
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Droplink
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 600
Languages:
- Language: en
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: Professional Pattern Card
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210730T123212Z
