---
ID: "905d269a-ea53-43ac-b71b-0da46da52663"
Parent: "b9a5d966-0d19-4bf1-ab61-67d2ef009b61"
Template: "b9a5d966-0d19-4bf1-ab61-67d2ef009b61"
Path: /sitecore/templates/Project/LionTrust/Content Types/EXM/Article Cards/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221017T132142Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\anascimento
    - ID: "bdeb100c-fb3b-4fd5-8fce-8a45ebe791f8"
      Hint: ArticleCards_CtaText
      Value: VIEW THE ARTICLE ➝
