---
ID: "e2ea67c3-87a3-45d1-ab5d-d6cb6c390fe3"
Parent: "acc33898-284a-4c43-b790-e6d8a566ea71"
Template: "acc33898-284a-4c43-b790-e6d8a566ea71"
Path: /sitecore/templates/Project/EIT/Content Types/Navigation/Social Link/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{8871A51E-2E85-4BF4-813E-22DC418118BD}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210624T083455Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
