---
ID: "4c2b45c1-96eb-458f-8171-6543ea38f132"
Parent: "6a29d78d-81f7-40ca-b968-cc40b3117544"
Template: "6a29d78d-81f7-40ca-b968-cc40b3117544"
Path: /sitecore/templates/Project/EIT/Content Types/Banner/Text and CTA/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221121T121022Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
