---
ID: "0029eeab-0c10-4f69-9777-d5242ed16689"
Parent: "a34b7c53-d58b-431c-af26-38d5fde6d46d"
Template: "363d9fa3-49ab-48b8-96ab-6838c77e9d70"
Path: /sitecore/content/LionTrustNew/Home/BTR Page/_Local/Our Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "21a76102-edd0-4248-98d3-b320c5e25909"
      Hint: OurValues_FirstBodyCopy
      Value: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus pharetra sem vel lacus rutrum, a imperdiet arcu faucibus. Cras hendrerit mattis erat, et accumsan risus facilisis eu. Proin ultrices risus dui. Nullam convallis arcu aliquam sapien condimentum tincidunt. Praesent sed cursus libero. Donec ultrices magna et libero pharetra, varius malesuada arcu fermentum.
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210823T154845Z
    - ID: "562dd82e-0639-4ce5-8379-a00b855fbf98"
      Hint: OurValues_SecondBodyCopy
      Value: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus pharetra sem vel lacus rutrum, a imperdiet arcu faucibus. Cras hendrerit mattis erat, et accumsan risus facilisis eu. Proin ultrices risus dui. Nullam convallis arcu aliquam sapien condimentum tincidunt. Praesent sed cursus libero. Donec ultrices magna et libero pharetra, varius malesuada arcu fermentum.&nbsp;
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\liontrust_admin
    - ID: "8196ccdd-b06b-433f-8445-6919a4d39216"
      Hint: OurValues_FirstTitle
      Value: Lorem ipsum
    - ID: "82e11a79-e14e-4140-be21-6eb9b623cf71"
      Hint: OurValues_Heading
      Value: Our Values
    - ID: "c78d6936-deca-4e02-b5e0-f76bd11bcf88"
      Hint: OurValues_SecondTitle
      Value: Lorem ipsum
    - ID: "cd3c0151-27b3-43e4-9b7d-b66b248529aa"
      Hint: OurValues_ThirdBodyCopy
      Value: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus pharetra sem vel lacus rutrum, a imperdiet arcu faucibus. Cras hendrerit mattis erat, et accumsan risus facilisis eu. Proin ultrices risus dui. Nullam convallis arcu aliquam sapien condimentum tincidunt. Praesent sed cursus libero. Donec ultrices magna et libero pharetra, varius malesuada arcu fermentum.&nbsp;
    - ID: "f71792b2-d652-4f8c-b6b2-73d5e67b1af1"
      Hint: OurValues_ThirdTitle
      Value: Lorem ipsum
