---
ID: "b2f7aae5-c7d5-4143-a91a-d80184bb7704"
Parent: "af865864-56fb-4a24-bacc-278c33c44041"
Template: "af865864-56fb-4a24-bacc-278c33c44041"
Path: /sitecore/templates/Project/LionTrust/Page Types/Fund Detail Page/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{CD1590E1-6573-4CC7-B0A9-E3BB6A9DADE4}">
        <r
          id="{29A12478-EBE8-4B5C-BF2E-871026066814}"
          ph="footer"
          uid="{CCBBB036-5788-4F78-AC6A-DF34C178F76C}" />
        <r
          id="{DD1D438A-3971-438B-B1C9-461415F43488}"
          ph="footer"
          uid="{A9D97645-8E0D-4192-A314-3437510B5AF8}" />
        <r
          id="{C728A955-DA1D-4700-B924-E0D35901DE4B}"
          ph="footer"
          uid="{B6CB773C-E731-4F36-B72A-AF5BFE57CA6F}" />
        <r
          ds="{BDC1F34D-BBD9-4887-81DF-2EB5DB933504}"
          id="{3322E03C-F4D5-4BF9-88AF-70C9AB775188}"
          par=""
          ph="footer"
          uid="{F100020C-98C6-4D33-BCCE-6C46079A6D08}" />
        <r
          ds="{CA74E9F1-9B48-44B9-95AA-235DF422EAC1}"
          id="{2BE3EC53-02FF-4EED-B3FC-5E4535185D73}"
          par=""
          ph="footer"
          uid="{30A0A4C8-974F-4822-9DCB-DE14881E0400}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210622T112737Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
