---
ID: "b2f7aae5-c7d5-4143-a91a-d80184bb7704"
Parent: "af865864-56fb-4a24-bacc-278c33c44041"
Template: "af865864-56fb-4a24-bacc-278c33c44041"
Path: /sitecore/templates/Project/LionTrust/Page Types/Fund Detail Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210622T112737Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
