---
ID: "267f8ba6-60e3-4a82-94ef-ba4e26b732f4"
Parent: "2e71a4d9-8115-47e6-973a-7de681370739"
Template: "2e71a4d9-8115-47e6-973a-7de681370739"
Path: /sitecore/templates/Project/LionTrust/Page Types/Insight Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210625T103235Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
