---
ID: "dc2708de-a316-439b-b8e2-ef72b7cf5f70"
Parent: "363d9fa3-49ab-48b8-96ab-6838c77e9d70"
Template: "363d9fa3-49ab-48b8-96ab-6838c77e9d70"
Path: /sitecore/templates/Project/LionTrust/Content Types/Listing/OurValues/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210816T143054Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "82e11a79-e14e-4140-be21-6eb9b623cf71"
      Hint: OurValues_Heading
      Value: $name
