---
ID: "b842b18a-e7d5-4f98-a723-b8876de74454"
Parent: "a8ce285e-e3d2-4a78-899c-e3c02cd5e4ae"
Template: "363d9fa3-49ab-48b8-96ab-6838c77e9d70"
Path: /sitecore/content/LionTrustNew/Home/About us/_Local/Our Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "21a76102-edd0-4248-98d3-b320c5e25909"
      Hint: OurValues_FirstBodyCopy
      Value: |
        
        We do not follow the herd and have the courage to have independence of thought. Our fund managers have the courage of their convictions and have differentiated and robust investment processes. The business has the courage to do the right thing, make decisive decisions and to be innovative and nimble.
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220311T114803Z
    - ID: "2d65d3d3-95d0-4fa4-ab20-4702211b97b5"
      Hint: OurValues_HeadingColor
      Value: "{ABC9B1B3-78C4-4493-A681-576EA253919E}"
    - ID: "562dd82e-0639-4ce5-8379-a00b855fbf98"
      Hint: OurValues_SecondBodyCopy
      Value: |
        
        We strive for excellence in our products, service and people so we can have a positive impact on clients and stakeholders. We pride ourselves on the quality of our fund management teams and the knowledge and ability of our staff across the business. We provide first-class service and are transparent about the management of our funds, portfolios and the business, communicating clearly and frequently.
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\TomG
    - ID: "8196ccdd-b06b-433f-8445-6919a4d39216"
      Hint: OurValues_FirstTitle
      Value: COURAGE
    - ID: "82e11a79-e14e-4140-be21-6eb9b623cf71"
      Hint: OurValues_Heading
      Value: Liontrust brand values
    - ID: "c78d6936-deca-4e02-b5e0-f76bd11bcf88"
      Hint: OurValues_SecondTitle
      Value: EXCELLENCE
    - ID: "cd3c0151-27b3-43e4-9b7d-b66b248529aa"
      Hint: OurValues_ThirdBodyCopy
      Value: |
        
        We seek to be a responsible company and investor. We uphold the highest standards of integrity in all of our actions, treating staff, clients and stakeholders fairly and with respect. We are committed to contributing to and benefiting the wider society, including through sustainability, financial education, diversity and equality.
    - ID: "f71792b2-d652-4f8c-b6b2-73d5e67b1af1"
      Hint: OurValues_ThirdTitle
      Value: GOOD CITIZENSHIP
