---
ID: "9e95064b-9e3c-41e0-9549-cc98776ac80a"
Parent: "1ba4a6be-be4d-4c3a-874f-485446a4a806"
Template: "1ba4a6be-be4d-4c3a-874f-485446a4a806"
Path: /sitecore/templates/Project/EIT/Content Types/Fund/FundDisclaimer/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210504T124820Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
