---
ID: "64097447-f9b7-4cd8-b8a4-12b96bc8bfff"
Parent: "f5f4baeb-c016-4edf-8fb7-48c99c63700f"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Feature/Listings/Generic Listing Module/_GenericListingFacetsConfig/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210630T163647Z
