---
ID: "da1fdf60-2fde-49a2-9075-89d1c515117e"
Parent: "d503b817-4813-4205-a29c-fd7fcfda3ffc"
Template: "d503b817-4813-4205-a29c-fd7fcfda3ffc"
Path: /sitecore/templates/Project/LionTrust/Content Types/Search/Site Search/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{265516B5-70B3-44C6-809F-77052C76EB21}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "2056e3a0-3765-4df0-8836-349180e8d7f5"
      Hint: SiteSearch_PageCount
      Value: 10
    - ID: "233579af-fd62-46a8-9571-be7637bc2a52"
      Hint: SiteSearch_SimilarResultsLabel
      Value: "No results found - showing similar results"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210625T101443Z
    - ID: "34d19244-ffea-42cc-8310-3d4bcf89b4f8"
      Hint: SiteSearch_ViewAll
      Value: All Results
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "7e350bba-b71b-49aa-910f-5316636cac17"
      Hint: SiteSearch_SearchLabel
      Value: Search again
    - ID: "83d03ce9-1f83-4f04-8d65-474ab9bfbfc0"
      Hint: SiteSearch_NoSearchResultsFoundLabel
      Value: No results found
    - ID: "94cae85f-6aed-4d42-ba9b-c487af809cc7"
      Hint: SiteSearch_FactsheetLinkText
      Value: Factsheet
