---
ID: "1edd1b67-b400-472f-97c3-2944bcbf5542"
Parent: "fef40064-216d-4888-93ef-a5e4a3d1e203"
Template: "fef40064-216d-4888-93ef-a5e4a3d1e203"
Path: /sitecore/templates/Project/LionTrust/Content Types/FourFundStats/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210507T140505Z
    - ID: "3dc4db39-af37-4bdc-b8a8-7c06458bb9b5"
      Hint: FourFundStats_FundSizeLabel
      Value: Fund Size
    - ID: "41a6502d-ce3f-4938-9746-1b6d0eb9a057"
      Hint: FourFundStats_FundLaunchDateLabel
      Value: Fund Launch Date
    - ID: "4d0f2400-c512-4457-bbe4-afe776d25fea"
      Hint: FourFundStats_NumberOfHoldingsLabel
      Value: Number of Holdings
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8e7a0a72-4f42-4fc3-8c5f-bb44152fd189"
      Hint: FourFundStats_ManagedByCurrentTeamForLabel
      Value: Managed by Current Team for
