---
ID: "ae4c5639-5063-405c-8333-e6b3c152be93"
Parent: "48f4678d-62f3-46de-b9dc-dac236878ef5"
Template: "48f4678d-62f3-46de-b9dc-dac236878ef5"
Path: /sitecore/templates/Project/Common/Content Types/Article Search Facet Configuration/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210503T091108Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
