---
ID: "e80ff551-ab3e-4f73-8fcb-7aa507b02214"
Parent: "d819abd4-0af0-43c5-be80-db899e810a78"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/content/Applications/WebEdit/Edit Frame Buttons/Feature/Listings/PerformanceCharts/Chart
DB: core
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210726T202851Z
