---
ID: "3032189b-31aa-4338-862c-62c499efbe02"
Parent: "e0022199-8fb7-4144-924e-bd9c9bc76bab"
Template: "66e09d5b-4f8e-4313-9df3-fa7e53fbe83a"
Path: "/sitecore/content/LionTrustNew/Home/Our Funds/How to invest/_Local/BC042 - Document Lister with Date/Liontrust ISA application form"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220301T161922Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JamesJ
    - ID: "a4a7f9dd-a218-4f33-b72a-7dc2251ccd43"
      Hint: LegacyDocument_DocumentTypes
      Type: Multilist
      Value: "{F55E7EB7-656F-499A-804D-23550BF1199F}"
    - ID: "c794210e-6107-4d69-841f-773cb9943bba"
      Hint: LegacyDocument_DownloadLink
      Value: |
        <link text="Download form" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{D2326421-0CC2-44DE-9136-003952B504EA}" />
    - ID: "eeb8db99-7da8-4973-adf7-bcf7b29eba79"
      Hint: LegacyDocument_DocumentName
      Value: Liontrust ISA application form
    - ID: "f47124a7-6a71-437b-bd00-455b0e9942cf"
      Hint: LegacyDocument_Date
      Value: 20220301T000000Z
