---
ID: "bb4b208f-56b9-4be4-9252-722c8f1c5090"
Parent: "042e8c61-e2b5-4f50-9ba4-9f8a36cdfff4"
Template: "042e8c61-e2b5-4f50-9ba4-9f8a36cdfff4"
Path: /sitecore/templates/Project/LionTrust/Content Types/Media Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210730T085349Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
