---
ID: "6ff0a081-0f87-4b8a-b83e-fda0cb403483"
Parent: "9d9ef67f-806e-4303-8ac8-9f091313b551"
Template: "9d9ef67f-806e-4303-8ac8-9f091313b551"
Path: /sitecore/templates/Project/LionTrust/Content Types/Fund/Fund class/__Standard Values
DB: master
SharedFields:
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0ce0e3bf-4431-4071-a2ea-a3b79d3f0093"
      Hint: FundClass_Name
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210608T100811Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
