---
ID: "ac9e73d4-409a-4bb5-9458-e1b891e5a4c5"
Parent: "7c94de4d-ce3e-4f7c-b4a6-e0b5c98f570e"
Template: "7c94de4d-ce3e-4f7c-b4a6-e0b5c98f570e"
Path: /sitecore/templates/Project/EIT/Content Types/Promo/Image Promo/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210420T100445Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "a9bfb452-12c3-4ad5-b58c-b8824eb16816"
      Hint: ImagePromo_Heading
      Value: $name
    - ID: "d73bd953-0554-47fa-b1ec-3053b7bb2826"
      Hint: ImagePromo_TextAlignment
      Value: "{79DA2651-4E23-42A5-B5B0-94E416E1A3E7}"
