---
ID: "3451bc75-f6ec-461b-949d-c8cdc8df5e6e"
Parent: "4ff89a02-aa31-4cb4-a3cf-5283fd504a2f"
Template: "4ff89a02-aa31-4cb4-a3cf-5283fd504a2f"
Path: /sitecore/templates/Project/LionTrust/Content Types/MyPreferences/Email Template/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211006T094236Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
