---
ID: "96b6ccd5-c54f-4053-be1b-3a0f0c597786"
Parent: "b9abd151-d602-4052-803a-3ec76e574d7c"
Template: "b9abd151-d602-4052-803a-3ec76e574d7c"
Path: /sitecore/templates/Project/LionTrust/Content Types/Article/Topic/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221111T183627Z
    - ID: "48a28820-bafd-4ddb-a968-75b57ee0925a"
      Hint: Topic_Value
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
