---
ID: "5f44334e-8b52-4bce-ab02-59629ac4dc98"
Parent: "64097447-f9b7-4cd8-b8a4-12b96bc8bfff"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/Feature/Listings/Generic Listing Module/_GenericListingFacetsConfig/Configuration/GenericListingFacetsConfig_ListingItemTypeFolder
DB: master
SharedFields:
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Droptree
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: Listing Item Type Folder
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210630T163647Z
