---
ID: "54066d14-e69c-4582-858a-5a1b1e645fb0"
Parent: "c94250df-9916-49e0-9927-bdd93a600ee1"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Feature/Search/_FundFacetConfig/Fund Facet Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210503T084129Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
