---
ID: "72b10f4b-8534-4ef5-9f8c-015eabfd4ddf"
Parent: "b20fde90-49de-419a-abc8-b2d0a9e0d2f6"
Template: "9fdcbfec-9863-4b84-8347-fb1a72a6c573"
Path: /sitecore/system/Settings/Feature/EXM/Salesforce Sync Settings
DB: master
SharedFields:
- ID: "3c1206f7-8bfd-4a84-a1ab-b16c4fde7f88"
  Hint: LastSyncDate
  Value: 20220622T230313Z
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220623T185158Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
