---
ID: "8cd7a1d9-8a35-4f1c-9bc8-23aae6a7bad0"
Parent: "e6722334-e286-48b4-b791-3ebf77b75e9b"
Template: "e6722334-e286-48b4-b791-3ebf77b75e9b"
Path: /sitecore/templates/Project/LionTrust/Content Types/Text/IFrame Module/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220218T092727Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "f31f2fc8-8cb8-48b5-a856-2a9d07045f25"
      Hint: UniqueId
      Value: ExternalWebContentExternalIFrame
