---
ID: "17126e13-4445-484f-81c2-63cfae326f26"
Parent: "c6aa3a82-ae10-4038-8506-b66a8eb24426"
Template: "c6aa3a82-ae10-4038-8506-b66a8eb24426"
Path: /sitecore/templates/Project/LionTrust/Content Types/Text/DividendFolder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{1FE597BD-084E-42FA-889B-7E4D14F2E08D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141016T152008
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
