---
ID: "d61fc1b3-9969-4f95-8796-fefbc864ca1f"
Parent: "e3d69a3a-69fc-4794-a43f-f61ef7dd6d6f"
Template: "48f4678d-62f3-46de-b9dc-dac236878ef5"
Path: /sitecore/content/LionTrustNew/Settings/Search Settings/Article Search Facet Config
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "08defe33-e04e-42ec-bf84-2872a25a73e1"
      Hint: ArticleFacetConfig_FundManagersLabel
      Value: Fund Managers
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210503T091716Z
    - ID: "3b09d368-cbf7-46bc-ad32-e922b9922667"
      Hint: ArticleFacetConfig_FundsLabel
      Value: Funds
    - ID: "3e5adee5-081e-40a4-bfa5-77a3449a93ed"
      Hint: ArticleFacetConfig_FundTeams
      Value: "{CE164BFD-E4D5-4ED3-B3D6-7E9528C34156}"
    - ID: "3f4bc13e-73fc-45d7-b858-8d54f2f4f51b"
      Hint: ArticleFacetConfig_Funds
      Value: "{92ABA568-F063-4316-A3B3-27AA0B4F154A}"
    - ID: "630f512c-b754-49c0-aedc-719960fe72d7"
      Hint: ArticleFacetConfig_CategoriesLabel
      Value: 
    - ID: "6591fe6b-328e-48a4-ae60-c25673c22f68"
      Hint: ArticleFacetConfig_FundTeamsLabel
      Value: Fund Teams
    - ID: "6fc49c6c-12c1-455e-951d-70beb68aee68"
      Hint: ArticleFacetConfig_FundManagers
      Value: "{55FD6306-D4DB-49BA-8471-07BDC35A1727}"
    - ID: "fddd0447-86ea-4e24-9f48-bcdc60d48922"
      Hint: ArticleFacetConfig_Categories
      Value: 
