---
ID: "eb8df2f0-969b-4215-ae3c-121c40a8e677"
Parent: "6c4c8ef8-77dd-45d7-ac84-618c21aa36a5"
Template: "6c4c8ef8-77dd-45d7-ac84-618c21aa36a5"
Path: /sitecore/templates/Project/LionTrust/Content Types/Newsletter Promo Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{75F26E7E-25B6-4470-A77D-A4A5B4B18246}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210415T105923Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
