---
ID: "c6cd6aaf-86fc-42c6-9760-6073b58e49b7"
Parent: "0a9343d7-9669-4c2a-9dbb-7972f5bd19f3"
Template: "ab8309b9-e012-4c89-88bb-6d364fb5e0db"
Path: /sitecore/content/LionTrustNew/Home/Insights/Blogs/2018/08/What does the new environment for bonds mean for investors
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 93300
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{BE7CC054-3034-4546-A8C2-8CE52A38EEDF}"
              p:before="*"
              s:ds="{ADEF647F-6595-40F9-A7E8-1DA2E8AAE367}"
              s:id="{67084541-3A58-4648-A597-DA8AA7C4F155}"
              s:par="DatasourceRule"
              s:ph="/content/side-content" />
            <r
              uid="{9140CD26-DD68-40E0-B247-D327136759BC}"
              p:after="r[@uid='{BE7CC054-3034-4546-A8C2-8CE52A38EEDF}']"
              s:ds="{3354D188-4714-4B6B-9584-B8A89BA288AF}"
              s:id="{67084541-3A58-4648-A597-DA8AA7C4F155}"
              s:par="DatasourceRule"
              s:ph="/content/side-content" />
            <r
              uid="{4F4456D9-701F-4EDD-9B17-6B91997BE9E5}"
              p:after="r[@uid='{9140CD26-DD68-40E0-B247-D327136759BC}']"
              s:ds=""
              s:id="{F329FEA4-20BC-4DEC-AEAD-C68B05C72A32}"
              s:par="Title=See also...&amp;RelatedPages={527F26E9-167E-4207-9B6A-18F018D3936C}|{035EFDA3-BC0A-43D6-9548-FC77F9116B6F}|{E30EB0CB-27E6-4CB5-A69E-0BE8D5EFF8A6}|{FC17F0A6-ECAA-4CD7-B80B-6E67FDE3251B}&amp;MaximumNoOfLinks=4"
              s:ph="/content/side-content" />
          </d>
        </r>
    - ID: "15f3afe1-ab21-4b6b-a434-4c0f7b927921"
      Hint: LegacyArticle_Authors
      Type: Treelist
      Value: "{D5724053-7941-45AF-8820-BF2103D61835}"
    - ID: "199ae724-078d-49b4-9e50-03f4c5e9e938"
      Hint: LegacyPresentationBase_BrowserTitle
      Value: "What does the new environment for bonds mean for investors? | What we think | Liontrust Asset Management PLC"
    - ID: "1c19356a-6e47-4d77-ba56-ade349f17b9d"
      Hint: LegacyArticle_Title
      Value: "What does the new environment for bonds mean for investors?"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180830T082305Z
    - ID: "34690273-d6b5-4cd5-8dfd-cc4f8aaefc81"
      Hint: LegacyHeroImagePageData_DarkCaption
      Type: Checkbox
      Value: 1
    - ID: "58b0791b-504e-423c-8d9e-e16c419353fa"
      Hint: LegacyArticle_BlogType
      Value: "{A0938A5B-ECE4-47D8-8564-421C0D816141}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\hayleya
    - ID: "6febf0b3-6bdb-43ea-9041-ca30ca342bb3"
      Hint: LegacyPresentationBase_SubNavigationMenu
      Value: "{4D8848D7-ABC1-4206-A6A9-21B174B7E945}"
    - ID: "8a3692c4-8014-4bdd-9f9f-74acfcc1c501"
      Hint: LegacyPresentationBase_ShortDescription
      Value: "With central banks finally tightening after a decade of loose policy, Kenny Watson examines this much-changed and more challenging backdrop for bonds and what investors can expect from the asset class."
    - ID: "aebdd235-46dd-490a-bae3-c613c670a8bf"
      Hint: LegacyPresentationBase_PageTitle
      Value: "What does the new environment for bonds mean for investors?"
    - ID: "b3a97116-0825-4197-a212-31849bdc54a2"
      Hint: LegacyHeroImagePageData_PageHeaderImage
      Value: |
        <image mediaid="{954451BD-9670-46F1-8035-1AF35EB613BD}" />
    - ID: "d8cf5da5-f35f-46d8-b15e-8b388dc01000"
      Hint: LegacyArticle_Content
      Value: |
        <p><strong>With quantitative tightening now in place and interest rates rising in the US and UK, we are in a very different environment for bonds to that seen over the last decade</strong>.</p>
        <p>Overall, we remain confident in the medium to long-term outlook for credit. On a shorter timeframe, however, the asset class is increasingly vulnerable to both negative sentiment and technical factors. There are a number of elements to unpick in the latter, all of which could potentially hit credit markets over the coming months to varying degrees.</p>
        <p>We believe it is possible to make money in this environment &ndash; particularly if you can use the various tools available in a flexible mandate &ndash; but it is important to understand exactly how these changing conditions could potentially affect fixed income markets.</p>
        <p style="margin-bottom: 8pt;">Brexit-related uncertainty still lingers, for example, a full two years after the historic vote, but some kind of compromise is expected to give us a softer exit. Increased geopolitical tensions such as President Trump&rsquo;s protectionist trade policies will continue to undermine spreads and add to volatility but we prefer to see this as an opportunity rather than a threat.</p>
        <p style="margin-bottom: 8pt;">Looking at supply, aggregate levels of euro credit are higher than in previous years and, given the increased volatility in financial markets, issuance is more focused on shorter funding windows. Issuance of sterling-denominated bonds has remained level, while supply in the US market is lower than in 2017, although there is a risk of a fresh spate as a result of merger and acquisition (M&amp;A) activity.</p>
        <p style="margin-bottom: 8pt;">New issue premiums, particularly in euros, have also moved higher, which is having a short-term impact on secondary spreads, seeing them widen out. Investor appetite remains strong, but given these increasing premiums, many are currently focusing on primary deals to get cash into the market. </p>
        <p> Despite these short-term factors, we believe fundamentals broadly continue to support credit, with global default rates very low and underlying economic growth still positive. Although the period of extraordinarily accommodative monetary policy is nearing its end, with the Federal Reserve hiking interest rates and the European Central Bank (ECB) the latest to join the tapering party,&nbsp; the unwinding will be slow and considered. </p>
        <p style="margin-bottom: 8pt;">Corporate leverage in the UK and eurozone remains at conservative levels and, while it is higher in the US, this reflects shareholder-friendly policies (share buybacks, special dividends and increased levels of M&amp;A) and a more advanced stage in the economic cycle.</p>
        <p style="margin-bottom: 8pt;">On the valuation front, credit spreads &ndash; the difference in yield between corporate and government bonds with the same maturity &ndash; have widened out significantly from their recent tight levels. Although below long-term averages, they remain supported by loose fiscal/monetary policies and the economic backdrop. Credit curves have steepened, offering value at the longer end while euro and sterling bonds have underperformed the US year to date, with the former pricing in the negatives outlined above.</p>
        <p style="margin-bottom: 8pt;">Taking all this into account, we remain positive on the asset class although returns will be more &ldquo;carry driven&rdquo; &ndash; meaning the income earned from the bond is outweighing the drop in its price &ndash; than they have been in recent years. We see selective opportunities for compression in spreads and so are seeking longer spread duration plays &ndash; ie more sensitive to spread changes &ndash; in our favoured sectors, including insurance and telecoms.</p>
        <p style="margin-bottom: 8pt;">Overall, the reduced level of spread correlation (a function of central banks reducing asset purchases) should create relative value opportunities within sectors and, coupled with cross market opportunities, this supports our view that credit will continue to deliver attractive income returns. Within this context, our favoured markets remain the UK and US over Europe and we continue to prefer investment grade over high yield.</p>
        <span>We reiterate, however, that flexible mandates can help generate returns while reducing volatility against more challenging backdrops.</span>
        <div><span><br>
        </span></div>
        <div>
        <p>For a comprehensive list of common financial words and terms, see our glossary <a href="https://www.liontrust.co.uk/benefits-of-investing/guide-financial-words-terms"><span style="color: #34b233;">here</span></a>.</p>
        <p><strong>Key Risks</strong></p>
        <p><strong>Past performance is not a guide to future performance. Do remember that the value of an investment and the income generated from them can fall as well as rise and is not guaranteed, therefore, you may not get back the amount originally invested and potentially risk total loss of capital.</strong> The issue of units/shares in Liontrust Funds may be subject to an initial charge, which will have an impact on the realisable value of the investment, particularly in the short term. Investments should always be considered as long term.</p>
        <p>Investment in Funds managed by the Sustainable Future Fixed Income team involves foreign currencies and may be subject to fluctuations in value due to movements in exchange rates. The value of fixed income securities will fall if the issuer is unable to repay its debt or has its credit rating reduced. Generally, the higher the perceived credit risk of the issuer, the higher the rate of interest. The Monthly Income Bond Fund has a Distribution Yield which is higher than the Underlying Yield because the fund distributes coupon income and the fund&rsquo;s expenses are charged to capital. This has the effect of increasing dividends while constraining the fund&rsquo;s capital appreciation. The Distribution Yield and the Underlying Yield is the same for the SF Corporate Bond Fund.</p>
        <p><strong>Disclaimer</strong></p>
        <span>This content should not be construed as advice for investment in any product or security mentioned, an offer to buy or sell units/shares of Funds mentioned, or a solicitation to purchase securities in any company or investment product. Examples of stocks are provided for general information only to demonstrate our investment philosophy.&nbsp; It contains information and analysis that is believed to be accurate at the time of publication, but is subject to change without notice. Whilst care has been taken in compiling the content of this document, no representation or warranty, express or implied, is made by Liontrust as to its accuracy or completeness, including for external sources (which may have been used) which have not been verified. It should not be copied, faxed, reproduced, divulged or distributed, in whole or in part, without the express written consent of Liontrust. Always research your own investments and (if you are not a professional or a financial adviser) consult suitability with a regulated financial adviser before investing.</span></div>
