---
ID: "54ce4152-98f4-4e2c-80b7-27433b0b76b2"
Parent: "084f0f8a-3d3d-469a-b9fc-9ff73bccdd06"
Template: "084f0f8a-3d3d-469a-b9fc-9ff73bccdd06"
Path: /sitecore/templates/Project/EIT/Page Types/Article Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221103T130952Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
