---
ID: "9c991e01-51f8-4f76-9577-a0143d79a63e"
Parent: "a538f9db-fba8-4e71-b026-33b8432f5029"
Template: "a538f9db-fba8-4e71-b026-33b8432f5029"
Path: /sitecore/templates/Project/EIT/Content Types/Fund/TwoColumnComponent/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0b7847a5-f42b-42e0-b4d0-3cb4350cee45"
      Hint: TwoColumnComponent_LeftPaddingSize
      Value: 0
    - ID: "1a02d0a6-1e81-4119-ab01-a0e90d5eb8a8"
      Hint: TwoColumnComponent_RightColumnSize
      Value: 5
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210513T170148Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "d3a375f2-cb82-4f2b-af60-550fc662a00d"
      Hint: TwoColumnComponent_RightPaddingSize
      Value: 1
    - ID: "f6a1dc1f-d9c0-40b8-9590-d5c58d1f2346"
      Hint: TwoColumnComponent_LeftColumnSize
      Value: 6
