---
ID: "b7b4b462-bf8e-4187-adc2-5ebbe2e983e1"
Parent: "5df77998-4ada-4367-9b3b-d51a2e547cb8"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/Feature/Navigation/_FooterConfiguration/Footer/FooterConfiguration_EmailCTAGoal
DB: master
SharedFields:
- ID: "1eb8ae32-e190-44a6-968d-ed904c794ebf"
  Hint: Source
  Value: "{0CB97A9F-CAFB-42A0-8BE1-89AB9AE32BD9}"
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Droptree
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 1200
Languages:
- Language: en
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: Email Goal
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210624T085127Z
