---
ID: "abfd5ec1-d929-4552-a88c-36137f9587c3"
Parent: "65820284-5849-482c-9894-a9a5091892fe"
Template: "65820284-5849-482c-9894-a9a5091892fe"
Path: /sitecore/templates/Project/LionTrust/Content Types/PerformanceCharts/Performance Chart/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{66461E0A-7825-474E-8528-1F49E5D5123B}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0a7a9253-28d8-4544-b566-43e9909eca08"
      Hint: PerformanceCharts_MaxRange
      Value: 100
    - ID: "18ad469c-30ab-420c-a9aa-1fe500163a10"
      Hint: PerformanceCharts_Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210726T201437Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "91102ff9-f609-4ade-a427-0676fca53279"
      Hint: PerformanceCharts_Scale
      Value: %
    - ID: "ae5bc6e7-8584-42d2-b908-37183fed6035"
      Hint: PerformanceCharts_Height
      Value: 400
    - ID: "ae97152e-d708-47ee-9f64-62cafd9d6929"
      Hint: PerformanceCharts_Width
      Value: 400
    - ID: "e350a26a-5cce-4a24-a220-90610cfe740c"
      Hint: PerformanceCharts_YRange
      Value: 10
