---
ID: "925adcdf-56e3-49e5-91f6-ca90d936f1a9"
Parent: "02cb5861-c91e-47d7-bd6a-a64f5504da52"
Template: "02cb5861-c91e-47d7-bd6a-a64f5504da52"
Path: /sitecore/templates/Project/LionTrust/Page Types/Investment Case/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210816T103616Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
