---
ID: "bdc1f34d-bbd9-4887-81df-2eb5db933504"
Parent: "de347e52-3823-4c3d-96a5-6dda2dcf0d85"
Template: "23ab5d04-7db2-4750-a193-819648ac037b"
Path: /sitecore/content/LionTrustNew/Global/Onboarding Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0d201af9-3ada-4859-8b60-c2da64c5f059"
      Hint: OnboardingConfiguration_PrivateProfileCard
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210610T094021Z
    - ID: "a2546c2d-e821-46f7-8042-d78f3f1ca8f1"
      Hint: OnboardingConfiguration_ProfessionalProfileCard
      Value: 
    - ID: "b2efa293-4240-4439-997f-ddac10179067"
      Hint: OnboardingConfiguration_Logo
      Value: |
        <image mediaid="{98A09831-DF76-4BFA-A05E-2EE4C55405D4}" />
