---
ID: "8af83fdb-f9d8-4b35-8c8e-c0f9465ed7b2"
Parent: "4be83316-f916-42c3-ac15-e86c6ad5b215"
Template: "f427e4f7-f934-4aa3-8fe6-61c719745c28"
Path: /sitecore/content/LionTrust New/Page Settings/Header Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210406T115341Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
