---
ID: "045202db-50c9-4bd6-9f52-58e46a72bbf6"
Parent: "7d79c77d-c8a7-4027-80eb-4d7c316358b0"
Template: "7d79c77d-c8a7-4027-80eb-4d7c316358b0"
Path: /sitecore/templates/Feature/Listings/Accordion/_AccordionRenderingParameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210420T140016Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
