---
ID: "fefb4041-8079-4381-a785-9803737105ca"
Parent: "8baa6e9e-ca51-4cbd-8e4e-ba53cafe8c17"
Template: "8baa6e9e-ca51-4cbd-8e4e-ba53cafe8c17"
Path: /sitecore/templates/Project/LionTrust/Content Types/Site Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210323T174221Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
