---
ID: "03846c43-db8c-445b-88c0-8cf5ee7fb9f1"
Parent: "75f26e7e-25b6-4470-a77d-a4a5b4b18246"
Template: "75f26e7e-25b6-4470-a77d-a4a5b4b18246"
Path: /sitecore/templates/Project/LionTrust/Content Types/Newsletter/Newsletter Promo/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210416T183952Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
