---
ID: "85c0c823-6757-4a55-a9c7-1efa888266d4"
Parent: "6da94e41-16fa-4afd-b55f-6c5866a768cb"
Template: "66e09d5b-4f8e-4313-9df3-fa7e53fbe83a"
Path: "/sitecore/content/LionTrustNew/Home/Our Funds/How to invest/_Local/BC042 - Document Lister/Liontrust JISA application form"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220301T162043Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JamesJ
    - ID: "a4a7f9dd-a218-4f33-b72a-7dc2251ccd43"
      Hint: LegacyDocument_DocumentTypes
      Type: Multilist
      Value: "{F55E7EB7-656F-499A-804D-23550BF1199F}"
    - ID: "c794210e-6107-4d69-841f-773cb9943bba"
      Hint: LegacyDocument_DownloadLink
      Value: |
        <link text="Download form" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{B9141400-7FCF-43C6-BA1A-E936AAAF8A7A}" />
    - ID: "eeb8db99-7da8-4973-adf7-bcf7b29eba79"
      Hint: LegacyDocument_DocumentName
      Value: Liontrust JISA application form
    - ID: "f47124a7-6a71-437b-bd00-455b0e9942cf"
      Hint: LegacyDocument_Date
      Value: 20220301T000000Z
