---
ID: "8ded0154-6aad-4935-a757-bb71b322106c"
Parent: "84cff857-8e94-4207-aa38-c58ba8f5041a"
Template: "84cff857-8e94-4207-aa38-c58ba8f5041a"
Path: /sitecore/templates/Project/LionTrust/Content Types/FundDisclaimer/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210504T124820Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
