---
ID: "de4379c9-0ea1-4daf-a9db-4c13ef8f385f"
Parent: "036480ed-d109-46ba-9105-1bd3d401d924"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/Feature/EXM/_ExmFooter/Footer/ExmFooterConfiguration_Social Links
DB: master
SharedFields:
- ID: "1eb8ae32-e190-44a6-968d-ed904c794ebf"
  Hint: Source
  Value: "query:./Social Links"
- ID: "21828437-ea4b-40a1-8c61-4ce60ea41db6"
  Hint: Validate Button
  Type: tree list
  Value: 
- ID: "337e20e1-999a-4eea-85ad-b58a03ae75cc"
  Hint: Quick Action Bar
  Type: tree list
  Value: 
- ID: "53c432c4-7122-4e2d-8296-db4184fd1735"
  Hint: Workflow
  Type: tree list
  Value: 
- ID: "9c903e29-650d-4af2-b9bd-526d5c14a1a5"
  Hint: Validator Bar
  Type: tree list
  Value: 
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Treelist
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: Social Links
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220107T163433Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
