---
ID: "77a4d58f-eb9e-43b9-ad78-f52b0ab3e23b"
Parent: "b274aa33-7d65-48ff-84c1-fbc59d404746"
Template: "b274aa33-7d65-48ff-84c1-fbc59d404746"
Path: /sitecore/templates/Project/LionTrust/Content Types/Fund/Fund Centre/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210818T140946Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "96028547-df10-4fea-bc33-3c73107e64e5"
      Hint: FundCentre_IFrameRootUrl
      Value: "https://digital.feprecisionplus.com/liontrustam/en-gb/liontrustam"
