---
ID: "123012f9-b1fd-4f00-8d47-8a20676d9964"
Parent: "a44eff3e-f314-45ff-9dca-2101e919b78a"
Template: "eca6e291-bb55-47ab-bd02-be76b1bc884f"
Path: /sitecore/system/Settings/Html Editor Profiles/Feature/Text/Rich Text/Configuration Type
DB: core
SharedFields:
- ID: "ff617570-33a4-4d0e-931e-ffeb9fab450f"
  Hint: Type
  Value: Sitecore.Shell.Controls.RichTextEditor.EditorConfiguration,Sitecore.Client
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20090811T153354
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
