---
ID: "e7ff1384-62f2-47a3-8a99-734bf9c66612"
Parent: "86212646-0646-4f63-b4db-6c3f247989b1"
Template: "86212646-0646-4f63-b4db-6c3f247989b1"
Path: /sitecore/templates/Project/LionTrust/Page Types/Search/__Standard Values
DB: master
SharedFields:
- ID: "8d5c486e-a0e3-4dbe-9a4a-cdff93594bda"
  Hint: IncludeInSearchResults
  Type: Checkbox
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210723T073215Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
