---
ID: "16d8ed3e-cc2e-4744-9b4e-05a63757dd08"
Parent: "bd5cdad6-3847-4b85-b0f4-98a63a5674c0"
Template: "bd5cdad6-3847-4b85-b0f4-98a63a5674c0"
Path: /sitecore/templates/Project/EIT/Content Types/Listing/Horizontal Scroll/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{8DFCA9BA-1024-47EE-8A43-93752E480BCB}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "08f9501f-35b1-4e66-96d0-8d04858a7ec5"
      Hint: HorizontalScroll_NumberOfItems
      Value: 3
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210429T115744Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "fd89a7af-a29a-42dc-949c-5ce8f66f9c71"
      Hint: HorizontalScroll_Title
      Value: $name
