---
ID: "941e47af-8eb6-4eef-bac4-b784ccc05a03"
Parent: "8e92c3fd-abfc-468b-8848-53b7aef8fb66"
Template: "8e92c3fd-abfc-468b-8848-53b7aef8fb66"
Path: /sitecore/templates/Project/EIT/Content Types/Article/Article Rich Text/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221121T164826Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
