---
ID: "4577fb3d-1d03-438f-8249-e358ef0a1e74"
Parent: "8a9d64d8-af76-4122-8917-e8d0cd7ac748"
Template: "f427e4f7-f934-4aa3-8fe6-61c719745c28"
Path: /sitecore/content/LionTrustNew/Page Settings/Headers/Journalist Header Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210406T115341Z
    - ID: "5d68cc82-ea43-4789-b892-0e49244f68d5"
      Hint: HeaderConfiguration_MenuItems
      Type: Treelist
      Value: |
        {D82BA38B-5FD6-4932-84D8-53606239F77B}
        {8B8EABCF-40C5-4D18-9CF2-9CC649FB44A9}
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
