---
ID: "b4800aec-e97c-480b-9f63-ad0ffded64cd"
Parent: "1cc5f9d2-1391-4305-96c9-8f1734e12b58"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Liontrust/Contact Us/Page/Fund Enquiries/Fund Enquiry/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210609T113349Z
